//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enable_Now_Konnektor_Bibliothek.locals {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class de_DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal de_DE() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Enable_Now_Konnektor_Bibliothek.locals.de-DE", typeof(de_DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Anhang {0} des Elements {1} konnte nicht analysiert werden. ähnelt.
        /// </summary>
        internal static string AttachementCrawlerMessage01 {
            get {
                return ResourceManager.GetString("AttachementCrawlerMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Konfigurationsdatei konnte nicht gelesen werden, weil sie entweder nicht vorhanden ist oder die Berechtigung fehlt (Pfad: {0}). ähnelt.
        /// </summary>
        internal static string ConfigReaderMessage01 {
            get {
                return ResourceManager.GetString("ConfigReaderMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Konfiguration konnte nicht gelesen werden, weil sie entweder nicht vorhanden ist, die Berechtigung fehlt oder fehlerhaft ist (Pfad: {0}). ähnelt.
        /// </summary>
        internal static string ConfigReaderMessage02 {
            get {
                return ResourceManager.GetString("ConfigReaderMessage02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Ergebnis des Converter-Service konnte nicht ausgewertet werden. Die Deserialisierung ist fehlgeschlagen. Das JSON ist ungültig. ähnelt.
        /// </summary>
        internal static string ConverterServiceMessage01 {
            get {
                return ResourceManager.GetString("ConverterServiceMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Anfrage an den Converter Service ist fehlgeschlagen. ähnelt.
        /// </summary>
        internal static string ConverterServiceMessage02 {
            get {
                return ResourceManager.GetString("ConverterServiceMessage02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Antwort des Converter Service konnte deserialisiert werden, enthält aber nicht das notwendige Feld {0}. ähnelt.
        /// </summary>
        internal static string ConverterServiceMessage03 {
            get {
                return ResourceManager.GetString("ConverterServiceMessage03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Element {0} soll nicht indexiert werden. ähnelt.
        /// </summary>
        internal static string CrawlerIndexerInterfaceMessage01 {
            get {
                return ResourceManager.GetString("CrawlerIndexerInterfaceMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Element {0} ist bereits im Index. Es existiert aber eine neuere Version. Lösche das Element {0} aus dem Index. ähnelt.
        /// </summary>
        internal static string CrawlerIndexerInterfaceMessage02 {
            get {
                return ResourceManager.GetString("CrawlerIndexerInterfaceMessage02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sende das Element {0} zum Indexieren. ähnelt.
        /// </summary>
        internal static string CrawlerIndexerInterfaceMessage03 {
            get {
                return ResourceManager.GetString("CrawlerIndexerInterfaceMessage03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Indexiere das Element {0}. ähnelt.
        /// </summary>
        internal static string CrawlerIndexerInterfaceMessage04 {
            get {
                return ResourceManager.GetString("CrawlerIndexerInterfaceMessage04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Überprüfen der Übereinstimmung der Werte beim Objekt {0} ähnelt.
        /// </summary>
        internal static string CrawlerIndexerInterfaceMessage05 {
            get {
                return ResourceManager.GetString("CrawlerIndexerInterfaceMessage05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Element {0} wurde erfolgreich indexiert. ähnelt.
        /// </summary>
        internal static string CrawlerIndexerInterfaceMessage06 {
            get {
                return ResourceManager.GetString("CrawlerIndexerInterfaceMessage06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Element {0} befindet sich bereits im Index. Es hat sich aber nicht verändert. ähnelt.
        /// </summary>
        internal static string CrawlerIndexerInterfaceMessage07 {
            get {
                return ResourceManager.GetString("CrawlerIndexerInterfaceMessage07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Indexieren des Elements {0} war nicht erfolgreich. ähnelt.
        /// </summary>
        internal static string CrawlerIndexerInterfaceMessage08 {
            get {
                return ResourceManager.GetString("CrawlerIndexerInterfaceMessage08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Autostart-Element konnte nicht analysiert werden. Es wird übersprungen. ähnelt.
        /// </summary>
        internal static string ElementCrawlerMessage01 {
            get {
                return ResourceManager.GetString("ElementCrawlerMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Eingabe &quot;{0}&quot; wurde nicht als Expression erkannt. ähnelt.
        /// </summary>
        internal static string ElementCrawlerMessage02 {
            get {
                return ResourceManager.GetString("ElementCrawlerMessage02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Eingabe &quot;{0}&quot; wurde als Variable erkannt. Die Variable ist &quot;{1}&quot;. ähnelt.
        /// </summary>
        internal static string ElementCrawlerMessage03 {
            get {
                return ResourceManager.GetString("ElementCrawlerMessage03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Eingabe &quot;{0}&quot; wurde als Erweiterungsmethode erkannt. Der Klassenname ist &quot;{1}&quot; und die Variable ist &quot;{2}&quot;. ähnelt.
        /// </summary>
        internal static string ElementCrawlerMessage04 {
            get {
                return ResourceManager.GetString("ElementCrawlerMessage04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es konnte keine Datenbankverbindung hergestellt werden. Der Name der Tabelle (ID des Jobs) darf nicht leer sein. ähnelt.
        /// </summary>
        internal static string ElementLogContextMessage01 {
            get {
                return ResourceManager.GetString("ElementLogContextMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die ID &quot;{0}&quot; entspricht nicht dem gültigen Muster von Enable Now. ähnelt.
        /// </summary>
        internal static string ElementMessage01 {
            get {
                return ResourceManager.GetString("ElementMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Anwendung läuft bereits seit {0} Minuten. Das übersteigt der maximal erlaubten Laufzeit. Das Programm wird daher beendet. ähnelt.
        /// </summary>
        internal static string ErrorControlMessage01 {
            get {
                return ResourceManager.GetString("ErrorControlMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beim Ablauf des Prozesses wurden {0} Fehler festgestellt. Das übersteigt die maximal erlaubte Anzahl. Das Programm wird daher beendet. ähnelt.
        /// </summary>
        internal static string ErrorControlMessage02 {
            get {
                return ResourceManager.GetString("ErrorControlMessage02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler: {0}. ähnelt.
        /// </summary>
        internal static string ErrorControlMessage3 {
            get {
                return ResourceManager.GetString("ErrorControlMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Aufruf der Erweiterungsmethode &quot;{0}&quot; mit dem Wert &quot;{1}&quot; ist fehlgeschlagen. Das Feld wird gelöscht. ähnelt.
        /// </summary>
        internal static string ExpressionEvaluatorMessage01 {
            get {
                return ResourceManager.GetString("ExpressionEvaluatorMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Führe die Erweiterungsmethode &quot;{0}&quot; mit dem Wert &quot;{1}&quot; aus. ähnelt.
        /// </summary>
        internal static string ExpressionEvaluatorMessage02 {
            get {
                return ResourceManager.GetString("ExpressionEvaluatorMessage02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Formulardaten gefunden (Name: &quot;{0}&quot;, Wert: &quot;{1}&quot;). ähnelt.
        /// </summary>
        internal static string HttpFormAuthenticationMessage01 {
            get {
                return ResourceManager.GetString("HttpFormAuthenticationMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sende das Authentifizierungsformular mit Anmeldedaten (URL: {0}). ähnelt.
        /// </summary>
        internal static string HttpFormAuthenticationMessage02 {
            get {
                return ResourceManager.GetString("HttpFormAuthenticationMessage02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Formular mit anderer ID wurde gefunden. Sende das Formular mit allen Parametern (URL: {0}). ähnelt.
        /// </summary>
        internal static string HttpFormAuthenticationMessage03 {
            get {
                return ResourceManager.GetString("HttpFormAuthenticationMessage03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rufe die Formularseite ab (URL: {0}). ähnelt.
        /// </summary>
        internal static string HttpFormAuthenticationMessage04 {
            get {
                return ResourceManager.GetString("HttpFormAuthenticationMessage04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sende eine HTTP-Anfrage an: {0} ähnelt.
        /// </summary>
        internal static string HttpRequestMessage01 {
            get {
                return ResourceManager.GetString("HttpRequestMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Server ist nicht erreichbar. Die Antwort auf die HTTP-Anfrage dauert zu lange und wurde deswegen abgebrochen. ähnelt.
        /// </summary>
        internal static string HttpRequestMessage02 {
            get {
                return ResourceManager.GetString("HttpRequestMessage02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Senden der HTTP-Anfrage ist fehlgeschlagen. ähnelt.
        /// </summary>
        internal static string HttpRequestMessage03 {
            get {
                return ResourceManager.GetString("HttpRequestMessage03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eine Authentifizierung ist erforderlich. ähnelt.
        /// </summary>
        internal static string HttpRequestMessage05 {
            get {
                return ResourceManager.GetString("HttpRequestMessage05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Proxy-Anmeldedaten sind leer. ähnelt.
        /// </summary>
        internal static string HttpRequestMessage4 {
            get {
                return ResourceManager.GetString("HttpRequestMessage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es wurde kein Job mit dem gespeicherten Index {0} gefunden. ähnelt.
        /// </summary>
        internal static string JobManagerMessage01 {
            get {
                return ResourceManager.GetString("JobManagerMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es wurde kein Job mit der ID {0} gefunden. ähnelt.
        /// </summary>
        internal static string JobManagerMessage02 {
            get {
                return ResourceManager.GetString("JobManagerMessage02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Index {0} des zu speichernden Jobs ist außerhalb des Rahmens. ähnelt.
        /// </summary>
        internal static string JobManagerMessage03 {
            get {
                return ResourceManager.GetString("JobManagerMessage03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Jobs konnten nicht gelesen werden. Möglicherweise existiert das Verzeichnis {0} nicht oder es fehlen die Berechtigungen. ähnelt.
        /// </summary>
        internal static string JobReaderMessage01 {
            get {
                return ResourceManager.GetString("JobReaderMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Konfiguration des Jobs ist fehlerhaft und konnte nicht deserialisiert werden. (Pfad: {0}) ähnelt.
        /// </summary>
        internal static string JobReaderMessage02 {
            get {
                return ResourceManager.GetString("JobReaderMessage02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Konfiguration des Jobs ist fehlerhaft. Prüfen Sie die URLs. (Pfad: {0}) ähnelt.
        /// </summary>
        internal static string JobReaderMessage03 {
            get {
                return ResourceManager.GetString("JobReaderMessage03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Datei {0} konnte nicht gelesen werden. ähnelt.
        /// </summary>
        internal static string JobReaderMessage04 {
            get {
                return ResourceManager.GetString("JobReaderMessage04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beginn: {0}. ähnelt.
        /// </summary>
        internal static string JobSchedulerMessage01 {
            get {
                return ResourceManager.GetString("JobSchedulerMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dauer: {0}. ähnelt.
        /// </summary>
        internal static string JobSchedulerMessage02 {
            get {
                return ResourceManager.GetString("JobSchedulerMessage02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ende: {0}. ähnelt.
        /// </summary>
        internal static string JobSchedulerMessage03 {
            get {
                return ResourceManager.GetString("JobSchedulerMessage03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Job-ID &quot;{0}&quot; tritt mehrfach auf. Vergeben Sie eine andere ID. ähnelt.
        /// </summary>
        internal static string JobSchedulerMessage04 {
            get {
                return ResourceManager.GetString("JobSchedulerMessage04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Job &quot;{0}&quot; wird übersprungen, da er nicht als Parameter übergeben wurde. ähnelt.
        /// </summary>
        internal static string JobSchedulerMessage05 {
            get {
                return ResourceManager.GetString("JobSchedulerMessage05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Pfad der Job-Konfigurationsdatei darf nicht leer sein. ähnelt.
        /// </summary>
        internal static string JobWriterMessage01 {
            get {
                return ResourceManager.GetString("JobWriterMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Element konnte nicht an den Index übermittelt werden. ähnelt.
        /// </summary>
        internal static string JsonIndexerMessage01 {
            get {
                return ResourceManager.GetString("JsonIndexerMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Element konnte nicht aus dem Index entfernt werden. ähnelt.
        /// </summary>
        internal static string JsonIndexerMessage02 {
            get {
                return ResourceManager.GetString("JsonIndexerMessage02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Job {0} wurde um {1} abgeschlossen.\n\nGefundene Dokumente: {2}\nIndexierte Dokumente: {3}\nGelöschte Dokumente: {4} ähnelt.
        /// </summary>
        internal static string MailClientMessage01 {
            get {
                return ResourceManager.GetString("MailClientMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die E-Mail konnte nicht verschickt werden. ähnelt.
        /// </summary>
        internal static string MailClientMessage02 {
            get {
                return ResourceManager.GetString("MailClientMessage02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Konnektor-Konfiguration konnte nicht geladen werden. ähnelt.
        /// </summary>
        internal static string MainWindowMessage01 {
            get {
                return ResourceManager.GetString("MainWindowMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die angeforderte Metadatei ist nicht vorhanden. ähnelt.
        /// </summary>
        internal static string MetaAnalyzerMessage02 {
            get {
                return ResourceManager.GetString("MetaAnalyzerMessage02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Entity-Datei darf nicht null sein. ähnelt.
        /// </summary>
        internal static string MetaAnalyzerMessage04 {
            get {
                return ResourceManager.GetString("MetaAnalyzerMessage04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Datei &quot;{0}&quot; existiert nicht. ähnelt.
        /// </summary>
        internal static string MetaFileReaderMessage01 {
            get {
                return ResourceManager.GetString("MetaFileReaderMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Inhalt der Datei ist ungültig und konnte nicht analysiert werden. ähnelt.
        /// </summary>
        internal static string MetaFileReaderMessage02 {
            get {
                return ResourceManager.GetString("MetaFileReaderMessage02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die HTTP-Anfrage für die Metadatei lieferte ein ungültiges Ergebnis, das nicht analysiert werden kann. ähnelt.
        /// </summary>
        internal static string MetaWebsiteReaderMessage01 {
            get {
                return ResourceManager.GetString("MetaWebsiteReaderMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Programm kann nicht ins standardmäßige Protokollverzeichnis schreiben. ähnelt.
        /// </summary>
        internal static string ProgramMessage01 {
            get {
                return ResourceManager.GetString("ProgramMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Argument &quot;{0}&quot; wurde als Job-ID erkannt. ähnelt.
        /// </summary>
        internal static string ProgramMessage02 {
            get {
                return ResourceManager.GetString("ProgramMessage02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starte alle Crawling Tasks ähnelt.
        /// </summary>
        internal static string PublicationCrawlerMessage01 {
            get {
                return ResourceManager.GetString("PublicationCrawlerMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analysiere das Element {0}. ähnelt.
        /// </summary>
        internal static string PublicationCrawlerMessage02 {
            get {
                return ResourceManager.GetString("PublicationCrawlerMessage02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beginne die Arbeit. ähnelt.
        /// </summary>
        internal static string PublicationCrawlerMessage03 {
            get {
                return ResourceManager.GetString("PublicationCrawlerMessage03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nichts zu tun. ähnelt.
        /// </summary>
        internal static string PublicationCrawlerMessage04 {
            get {
                return ResourceManager.GetString("PublicationCrawlerMessage04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es sind noch {0} Elemente in der Warteschlange. ähnelt.
        /// </summary>
        internal static string PublicationCrawlerMessage05 {
            get {
                return ResourceManager.GetString("PublicationCrawlerMessage05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Element {0} konnte nicht vollständig analysiert werden. Es wird daher übersprungen. ähnelt.
        /// </summary>
        internal static string PublicationCrawlerMessage07 {
            get {
                return ResourceManager.GetString("PublicationCrawlerMessage07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dieser Crawler-Thread beendet seine Arbeit. ähnelt.
        /// </summary>
        internal static string PublicationCrawlerMessage08 {
            get {
                return ResourceManager.GetString("PublicationCrawlerMessage08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Datenbank wurde initialisiert und alle gespeicherten Elemente wurde auf &quot;nicht gefunden&quot; gesetzt. ähnelt.
        /// </summary>
        internal static string PublicationCrawlerMessage09 {
            get {
                return ResourceManager.GetString("PublicationCrawlerMessage09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die nicht gefundenen Elemente wurden gelöscht. ähnelt.
        /// </summary>
        internal static string PublicationCrawlerMessage10 {
            get {
                return ResourceManager.GetString("PublicationCrawlerMessage10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die ID des Jobs darf nicht leer sein. Der Statistik-Service konnte nicht erstellt werden. ähnelt.
        /// </summary>
        internal static string StatisticsMessage01 {
            get {
                return ResourceManager.GetString("StatisticsMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gefundene Dokumente: {0}. ähnelt.
        /// </summary>
        internal static string StatisticsMessage02 {
            get {
                return ResourceManager.GetString("StatisticsMessage02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Autostart-Elemente: {0}. ähnelt.
        /// </summary>
        internal static string StatisticsMessage03 {
            get {
                return ResourceManager.GetString("StatisticsMessage03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unveränderten Dokumente: {0}. ähnelt.
        /// </summary>
        internal static string StatisticsMessage04 {
            get {
                return ResourceManager.GetString("StatisticsMessage04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Übersprungene Dokumente: {0}. ähnelt.
        /// </summary>
        internal static string StatisticsMessage05 {
            get {
                return ResourceManager.GetString("StatisticsMessage05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Indexierten Dokumente: {0}. ähnelt.
        /// </summary>
        internal static string StatisticsMessage06 {
            get {
                return ResourceManager.GetString("StatisticsMessage06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entfernten Dokumente: {0}. ähnelt.
        /// </summary>
        internal static string StatisticsMessage07 {
            get {
                return ResourceManager.GetString("StatisticsMessage07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Datum {0} konnte nicht geparst werden. Es wird stattdessen das heutige Datum verwendet. ähnelt.
        /// </summary>
        internal static string UtilMessage01 {
            get {
                return ResourceManager.GetString("UtilMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der reguläre Ausdruck &quot;{0}&quot; ist ungültig. ähnelt.
        /// </summary>
        internal static string ValidatorMessage01 {
            get {
                return ResourceManager.GetString("ValidatorMessage01", resourceCulture);
            }
        }
    }
}
